### ISSUE TITLE
node:crypto

### ISSUE THREAD

**Issue by arashisec** [justNoOneHere/MnemonicBalanceChecker#4]
get this error

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:crypto'
Require stack:
- /content/drive/MyDrive/mbc/node_modules/@noble/hashes/cryptoNode.js
- /content/drive/MyDrive/mbc/node_modules/@noble/hashes/utils.js
- /content/drive/MyDrive/mbc/node_modules/@noble/hashes/_sha2.js
- /content/drive/MyDrive/mbc/node_modules/@noble/hashes/sha256.js
- /content/drive/MyDrive/mbc/node_modules/bip39/src/index.js
- /content/drive/MyDrive/mbc/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/content/drive/MyDrive/mbc/node_modules/@noble/hashes/cryptoNode.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/content/drive/MyDrive/mbc/node_modules/@noble/hashes/cryptoNode.js',
    '/content/drive/MyDrive/mbc/node_modules/@noble/hashes/utils.js',
    '/content/drive/MyDrive/mbc/node_modules/@noble/hashes/_sha2.js',
    '/content/drive/MyDrive/mbc/node_modules/@noble/hashes/sha256.js',
    '/content/drive/MyDrive/mbc/node_modules/bip39/src/index.js',
    '/content/drive/MyDrive/mbc/index.js'
  ]
}

i was install like this :
npm install fs axios bip39 hdkey ethers ethereumjs-util prompt-sync

**Comment by arashisec** [comment]
btw I'm using Google Colab

**Comment by justNoOneHere** [comment]
It's not compatible with google colab..

**Comment by arashisec** [comment]
Ah I see. Thanks a lot.
